# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Cortex Grounded Query Generator for Agentic Workflows."""

from typing import Any

from common.mcp.schema_provider import CortexSchemaProvider


class CortexQueryGenerator:
    """Constructs grounded, verified BigQuery SQL queries against Cortex models."""

    def __init__(self, schema_provider: CortexSchemaProvider) -> None:
        self.schema_provider = schema_provider

    def generate_sample_query(
        self,
        product_type: str,
        table_name: str | None = None,
        project_id: str = "YOUR_PROJECT_ID",
        dataset_id: str = "cortex7_data_products",
        limit: int = 50,
    ) -> dict[str, Any]:
        """Generates a starter grounded query for a specific Cortex data product table."""
        product = self.schema_provider.get_product_schema(product_type)
        if not product:
            return {
                "error": f"Data product '{product_type}' not found.",
                "available_products": [p["type"] for p in self.schema_provider.list_products()],
            }

        tables = product.get("tables", {})
        if not tables:
            return {
                "error": f"No tables found for data product '{product_type}'.",
            }

        target_table_key = table_name if table_name in tables else list(tables.keys())[0]
        table_info = tables[target_table_key]
        fields = table_info.get("fields", [])

        # Select first 10 representative fields or all if fewer
        field_names = [f.get("name") for f in fields if f.get("name")]
        selected_fields = field_names[:10] if len(field_names) > 10 else field_names
        select_clause = ",\n  ".join(selected_fields) if selected_fields else "*"

        full_table_ref = f"`{project_id}.{dataset_id}.{product_type}_{target_table_key}`"

        sql = f"""-- Grounded query generated by Cortex MCP Server for {product.get("display_name")}
SELECT
  {select_clause}
FROM
  {full_table_ref}
WHERE
  -- Add standard enterprise partition/filter conditions:
  -- posting_date_budat >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)
LIMIT {limit};"""

        return {
            "product_type": product_type,
            "table_name": target_table_key,
            "full_table_ref": full_table_ref,
            "sql": sql,
            "description": table_info.get("description", ""),
            "available_fields_count": len(fields),
        }
